[build-system]
requires = [
    "openpyxl", 
    "numpy", 
    "pandas", 
    "regex",  
    "konlpy", 
    "setuptools",
    "mecab-python",
    "mecab-python3",
    "rapidfuzz",
    "jamo",
    "wheel"
    ],
build-backend = "setuptools.build_meta"